/**
 * Built-in skill catalog — descriptor metadata for every skill (RFC LP-16 — skills.ts landmine decomposition).
 *
 * Pure data extracted verbatim from skills.ts; the module re-imports it. Types
 * come from ./skill-types to avoid an import cycle.
 */

import type {
  SkillDescriptor,
} from "./skill-types";

export const SKILL_CATALOG: SkillDescriptor[] = [
  {
    id: "hover-reveal-navigation",
    name: "Hover Reveal Navigation",
    description:
      "Expose hover-dependent menus or hidden targets with an explicit hover, verify, then act sequence.",
    tags: ["workflow", "hover", "navigation", "reveal"],
    triggers: [
      "hover menus",
      "dropdown appears on hover",
      "hidden target must be revealed before click",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "hover_element",
      "click_element",
      "read_element",
      "update_notes",
    ],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "Do not assume hover succeeded just because the pointer moved.",
      "Verify revealed content before clicking into it.",
    ],
  },
  {
    id: "budget-aware-execution",
    name: "Budget Aware Execution",
    description:
      "Shift into a conservation mode when the workflow is at risk of exhausting turn budget before completion.",
    tags: ["workflow", "budget", "planning", "verification"],
    triggers: [
      "remaining turns are low",
      "hover or exploratory workflow is eating budget",
      "must avoid max-turns waste",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "read_element",
      "update_notes",
      "click_element",
    ],
    discouragedTools: ["done"],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "Prefer consolidation over exploration.",
      "Surface partial progress rather than burning the final turns on blind retries.",
    ],
  },
  {
    id: "transactional-act-check-act",
    name: "Transactional Act Check Act",
    description:
      "Execute a state-changing action, verify the page state, then continue with fresh grounding.",
    tags: ["workflow", "transactional", "verification", "mutation"],
    triggers: [
      "act then verify then continue",
      "inspect before mutating",
      "confirm-gated workflow",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "read_element",
      "click_element",
      "type_text",
      "dismiss_overlays",
      "update_notes",
    ],
    discouragedTools: ["done"],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "Prefer sequential execution.",
      "Require fresh grounding after mutation.",
    ],
  },
  {
    id: "cart-modify-checkout",
    name: "Cart Modify Checkout",
    description:
      "Modify an existing cart state, verify the result, then apply incentives and proceed to checkout safely.",
    tags: ["workflow", "shopping", "cart", "checkout"],
    triggers: [
      "swap item in cart",
      "replace product and keep cart state",
      "apply coupon and checkout",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "find_element",
      "click_element",
      "type_text",
      "read_element",
      "update_notes",
    ],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: ["Read cart state before and after mutation."],
  },
  {
    id: "email-reply-careful",
    name: "Email Reply Careful",
    description:
      "Read an email, extract the reply requirements, preserve language and tone context, then draft or send only after verifying the recipient and content.",
    tags: ["workflow", "email", "communication", "composition", "safety"],
    packId: "communication-workflows",
    triggers: [
      "reply to email",
      "respond to mail",
      "draft an email reply",
      "send a contextual email response",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "read_element",
      "update_notes",
      "type_text",
      "click_element",
    ],
    discouragedTools: ["done", "click_coordinates", "press_key"],
    capabilityNeeds: [
      "read_context",
      "compose_response",
      "submit_response",
      "verify_posted",
    ],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "Match the source email's language and register unless the user asks otherwise.",
      "Do not invent facts, commitments, dates, names, or recipients.",
      "Verify the draft and recipient before any send action.",
      "If the user asks to reply, respond, confirm, accept, or decline to a sender and does not say draft-only, the task requires sending the reply.",
      "After sending, verify real feedback such as sent-mail navigation, the message in the thread, a toast, or a changed email list state instead of re-reading the old draft.",
    ],
  },
  {
    id: "thread-message-careful",
    name: "Thread Message Careful",
    description:
      "Read a chat, channel, comment, or message thread, preserve audience, language, and tone context, then post a grounded reply to the correct thread.",
    tags: ["workflow", "messaging", "thread", "communication", "context"],
    triggers: [
      "reply in the thread",
      "post to the channel",
      "respond in chat",
      "send a message in the team thread",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "read_element",
      "update_notes",
      "type_text",
      "click_element",
    ],
    discouragedTools: ["done", "click_coordinates", "press_key"],
    capabilityNeeds: [
      "read_context",
      "compose_response",
      "submit_response",
      "verify_posted",
    ],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "Identify the exact thread, speaker, audience, language, and tone before composing.",
      "Preserve owners, deadlines, deliverables, blockers, and unresolved questions.",
      "Do not post if the target thread or audience is uncertain.",
      "If the user explicitly asks to reply, send, or post, treat a visible verified draft plus a visible Send/Post button as ready to submit; do not keep re-reading the same draft.",
      "After posting, verify real feedback such as the new message in the thread, a list update, a toast, or composer clearing instead of re-reading the old draft.",
    ],
  },
  {
    id: "crm-ticket-update",
    name: "CRM Ticket Update",
    description:
      "Update a CRM or support ticket record by reading the case context, applying requested field changes, and adding a grounded internal note.",
    tags: ["workflow", "crm", "ticket", "record-update", "support"],
    triggers: [
      "update support ticket",
      "set ticket status",
      "set ticket priority",
      "change ticket dropdown",
      "add internal note",
      "escalate CRM case",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "read_element",
      "update_notes",
      "select_option",
      "type_text",
      "set_checkbox",
      "click_element",
    ],
    discouragedTools: ["done", "click_coordinates"],
    capabilityNeeds: [
      "read_context",
      "update_record",
      "add_note",
      "verify_saved",
    ],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "Read the customer issue and ticket properties before changing fields.",
      "Update only fields supported by the request or visible ticket context.",
      "Use select_option for native status, priority, assignee, or category controls; use click_element only for custom dropdowns after the options are visible.",
      "If escalation is requested and no explicit escalation field is visible, use the ticket's priority field as the escalation-equivalent control and set it to Urgent when the impact supports escalation.",
      "Internal notes should include issue, impact, account context, and next step when available.",
    ],
  },
  {
    id: "chart-value-extraction",
    name: "Chart Value Extraction",
    description:
      "Extract requested values from dashboards or charts using structured chart evidence before pointer exploration.",
    tags: ["workflow", "chart", "dashboard", "data-extraction"],
    triggers: [
      "chart value",
      "dashboard metric",
      "read the chart",
      "bar chart",
      "line chart",
      "pie chart",
    ],
    maturity: "candidate",
    preferredTools: [
      "inspect_chart",
      "read_page",
      "read_element",
      "update_notes",
    ],
    discouragedTools: [
      "click_element",
      "navigate",
      "type_text",
      "select_option",
      "click_coordinates",
      "done",
    ],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "Prefer structured chart and SVG evidence before any pointer exploration.",
      "Treat chart/dashboard extraction as read-only; do not click Run, Refresh, report edit, drilldown, export, filter, or navigation controls unless the user explicitly asks to change the chart.",
      "When the user asks for one chart value, answer with exactly one numeric value and the requested unit; keep supporting counts, totals, timestamps, and axis ranges out of the final answer.",
      "When the user asks for a chart label and count, answer as 'Label: count' with one numeric count; do not repeat the count or include percentages, totals, axis ranges, or tie details.",
      "Completion requires a concrete requested chart value, not just reaching the chart page.",
    ],
  },
  {
    id: "search-answer-extraction",
    name: "Search Answer Extraction",
    description:
      "Search, open or read the best result, extract the requested fact, then answer explicitly.",
    tags: ["workflow", "search", "knowledge", "answer-extraction"],
    triggers: [
      "search knowledge",
      "knowledge base",
      "search results",
      "find the answer",
      "look up and answer",
    ],
    maturity: "candidate",
    preferredTools: [
      "search_knowledge_base",
      "read_page",
      "find_element",
      "type_text",
      "click_element",
      "read_element",
      "update_notes",
    ],
    discouragedTools: ["scroll_page", "click_coordinates"],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "Opening a result is intermediate.",
      "Prefer exact-question terms over broad paraphrases when searching.",
      "For knowledge-base answer questions, call search_knowledge_base first so search, result ranking, article reading, and answer extraction happen as one grounded read-only workflow.",
      "Compare result snippets or titles before opening; do not assume the first result is the answer.",
      "Completion requires a final answer that contains the requested fact.",
    ],
  },
  {
    id: "list-filter-workflow",
    name: "List Filter Workflow",
    description:
      "Apply list or table filters by setting a condition, running it, and verifying filtered state.",
    tags: ["workflow", "list", "table", "filter"],
    triggers: [
      "filter list",
      "apply filter",
      "filter builder",
      "condition builder",
      "show records where",
    ],
    maturity: "candidate",
    preferredTools: [
      "apply_list_filter",
      "inspect_table",
      "inspect_filter_state",
      "apply_list_action",
      "read_page",
      "update_notes",
    ],
    discouragedTools: [
      "find_element",
      "click_element",
      "select_option",
      "type_text",
      "inspect_hidden",
      "xray_page",
      "scroll_page",
      "click_coordinates",
      "done",
    ],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "When the request gives explicit field/operator/value conditions, use apply_list_filter before manual filter-builder clicks.",
      "Do not open the filter builder for explicit structured conditions unless apply_list_filter reports it cannot apply the request.",
      "Opening the filter builder is not completion.",
      "Verify an applied condition through query state, filter chips, or changed rows.",
    ],
  },
  {
    id: "list-sort-workflow",
    name: "List Sort Workflow",
    description:
      "Sort a list or table by the requested column and verify resulting sort state.",
    tags: ["workflow", "list", "table", "sort"],
    triggers: [
      "sort list",
      "sort table",
      "order by",
      "ascending",
      "descending",
      "sort column",
    ],
    maturity: "candidate",
    preferredTools: [
      "apply_list_sort",
      "inspect_table",
      "read_page",
      "update_notes",
    ],
    discouragedTools: [
      "find_element",
      "click_element",
      "scroll_page",
      "type_text",
      "click_coordinates",
      "done",
    ],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "When the request gives explicit sort fields and directions, use apply_list_sort before manual column-header or list-menu clicks.",
      "For multi-field sort requests, include every requested field and direction in one apply_list_sort call rather than sorting one header at a time.",
      "Do not open personalization/list configuration for sorting unless the structured sort helper reports unsupported fields.",
      "Completion requires URL, header, or row-order evidence that sorting changed.",
    ],
  },
  {
    id: "list-row-action-workflow",
    name: "List Row Action Workflow",
    description:
      "Select rows in a ServiceNow list/table and apply a selected-row action such as delete or mark duplicate.",
    tags: ["workflow", "list", "table", "row-action"],
    triggers: [
      "delete selected rows",
      "delete records",
      "mark duplicates",
      "selected rows action",
      "list action",
    ],
    maturity: "candidate",
    preferredTools: [
      "inspect_table",
      "apply_list_action",
      "inspect_filter_state",
      "read_page",
      "update_notes",
    ],
    discouragedTools: [
      "find_element",
      "click_element",
      "select_option",
      "type_text",
      "inspect_hidden",
      "xray_page",
      "click_coordinates",
      "done",
    ],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "Use inspect_table first to identify exact row identifiers and avoid acting on the wrong record.",
      "Use apply_list_action when the target rows and selected-row action are visible in a ServiceNow list.",
      "Do not infer hidden row identities; if the row cannot be uniquely identified, inspect or filter the list first.",
      "Completion requires evidence that the action ran and the affected rows or resulting status changed.",
    ],
  },
  {
    id: "catalog-order-workflow",
    name: "Catalog Order Workflow",
    description:
      "Configure a catalog item with requested quantity/options and continue through cart/order confirmation.",
    tags: ["workflow", "catalog", "order", "configuration"],
    triggers: [
      "order catalog item",
      "service catalog",
      "hardware catalog item",
      "hardware store",
      "catalog item with options",
      "configure item",
      "request item",
    ],
    maturity: "candidate",
    preferredTools: [
      "configure_catalog_item",
      "inspect_catalog_item",
      "set_checkbox",
      "type_text",
      "select_option",
      "click_element",
      "read_page",
      "update_notes",
    ],
    discouragedTools: ["scroll_page", "click_coordinates", "done"],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "Product detail page reached is intermediate.",
      "After reaching the item page, configure requested quantity/options and submit in the same workflow rather than reporting that the page is ready.",
      "Completion requires configured requested options and request/order confirmation.",
    ],
  },
  {
    id: "servicenow-module-navigation",
    name: "ServiceNow Module Navigation",
    description:
      "Resolve and open ServiceNow application navigator modules by metadata instead of manual menu or global search exploration.",
    tags: ["workflow", "servicenow", "navigation", "module"],
    packId: "servicenow-platform",
    triggers: [
      "ServiceNow module",
      "application navigator",
      "navigate to the module",
      "module of the application",
      "module in the application",
    ],
    maturity: "candidate",
    preferredTools: [
      "open_servicenow_module",
      "read_page",
      "done",
      "update_notes",
    ],
    discouragedTools: [
      "navigate",
      "type_text",
      "press_key",
      "scroll_page",
      "click_coordinates",
    ],
    contextScope: "turn",
    verifierMode: "deterministic",
    atomic: true,
    requiredEvidenceTypes: ["navigation_reached", "goal_state_verified"],
    notes: [
      "Use ServiceNow module metadata before manual application navigator clicks.",
      "Do not call navigate with a search query inside ServiceNow.",
    ],
  },
  {
    id: "structured-form-fill",
    name: "Structured Form Fill",
    description:
      "Fill a multi-field form with explicit field mapping and submit-last discipline.",
    tags: ["workflow", "forms", "data-entry"],
    triggers: [
      "fill form",
      "multi-field data entry",
      "choose values then submit",
      "configure product options",
      "upload file",
      "attach file",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "type_text",
      "select_option",
      "set_checkbox",
      "upload_file",
      "click_element",
    ],
    discouragedTools: ["press_key"],
    contextScope: "turn",
    verifierMode: "deterministic",
    notes: [
      "Map values to fields before typing.",
      "For configurators, verify any derived total, price, or summary after changing options before finishing.",
      "If same-page validation errors appear after submit, repair the named fields and resubmit instead of treating validation as completion.",
    ],
  },
  {
    id: "progressive-repeatable-form",
    name: "Progressive Repeatable Form",
    description:
      "Create, fill, and verify repeatable form groups that appear after Add another/Add item controls.",
    tags: ["workflow", "forms", "repeatable", "progressive", "data-entry"],
    triggers: [
      "add another section",
      "add multiple experience entries",
      "create repeated form sections",
      "fill repeatable rows in order",
      "add item three times then fill fields",
    ],
    maturity: "candidate",
    preferredTools: [
      "get_profile_fields",
      "read_page",
      "click_element",
      "type_text",
      "select_option",
      "set_checkbox",
      "update_notes",
    ],
    discouragedTools: ["press_key", "click_coordinates"],
    contextScope: "turn",
    verifierMode: "deterministic",
    notes: [
      "Count existing repeated groups before adding new ones.",
      "Re-ground after Add another/Add item controls because element ids and field groups can change.",
      "Map values by group label or index, not by field order alone.",
    ],
  },
  {
    id: "multi-step-form-wizard",
    name: "Multi-Step Form Wizard",
    description:
      "Complete forms split across Next/Back/Review steps, including conditional fields that appear after earlier choices.",
    tags: ["workflow", "forms", "wizard", "conditional", "data-entry"],
    triggers: [
      "multi-step form",
      "form wizard",
      "continue through review",
      "conditional fields",
      "next step then submit",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "type_text",
      "select_option",
      "set_checkbox",
      "click_element",
      "read_element",
      "update_notes",
    ],
    discouragedTools: ["press_key", "click_coordinates"],
    contextScope: "turn",
    verifierMode: "deterministic",
    notes: [
      "Treat each Next/Continue click as a state transition that requires fresh grounding.",
      "After selecting options that reveal conditional fields, fill and verify the revealed requirements before advancing.",
      "Use the review step as evidence before final submit.",
    ],
  },
  {
    id: "consequential-action-consent",
    name: "Consequential Action Consent",
    description:
      "Prepare workflows that may send, submit, publish, purchase, delete, confirm, or otherwise create real-world consequences, then stop for approval when user intent is unclear or approval is requested.",
    tags: ["workflow", "consent", "approval", "safety"],
    triggers: [
      "wait for approval before final action",
      "ask before submitting",
      "prepare but do not send",
      "draft and wait for confirmation",
      "final approval required",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "read_element",
      "update_notes",
      "type_text",
      "select_option",
      "set_checkbox",
      "click_element",
      "clarify",
    ],
    discouragedTools: ["done", "click_coordinates", "press_key"],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "Treat consequential final actions as approval-gated unless the user clearly authorized them.",
      "If the user's policy is unclear, ask whether to execute final actions or stop for approval.",
      "Preparation and verification may continue; final execution must wait for consent when requested or ambiguous.",
    ],
  },
  {
    id: "job-application-assistant",
    name: "Job Application Assistant",
    description:
      "Fill or prepare job, career, vacancy, CV, or resume application workflows, verify the application data, and stop before final submit unless explicit approval is obtained.",
    tags: ["workflow", "jobs", "application", "forms", "consent"],
    triggers: [
      "job application",
      "apply for a job",
      "career application",
      "submit resume",
      "fill job form and wait for approval",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "read_element",
      "find_element",
      "get_profile_fields",
      "update_notes",
      "type_text",
      "select_option",
      "set_checkbox",
      "upload_file",
      "click_element",
      "clarify",
    ],
    discouragedTools: ["done", "click_coordinates", "press_key"],
    capabilityNeeds: ["read_context", "update_record", "verify_saved"],
    contextScope: "turn",
    verifierMode: "hybrid",
    atomic: true,
    notes: [
      "Do not invent personal data, salary expectations, legal answers, or availability.",
      "Copy user-supplied long-form answers exactly unless the user explicitly asks for rewriting.",
      "Treat question-like application labels, such as why a company matters, as fields to fill rather than report prompts.",
      "Fill and verify requested fields, then summarize what is ready before final submit.",
      "Final application submission is a consequential action and must be approval-gated by runtime policy.",
    ],
  },
  {
    id: "ashby-job-application-assistant",
    name: "Ashby Job Application Assistant",
    description:
      "Fill Ashby-hosted job applications by label, preserve supplied application answers exactly, verify live field values, and stop before Submit Application unless explicitly approved.",
    tags: ["workflow", "jobs", "application", "forms", "ashby", "consent"],
    triggers: [
      "Ashby job application",
      "jobs.ashbyhq.com application",
      "Ashby application form",
      "Submit Application on Ashby",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "read_element",
      "find_element",
      "get_profile_fields",
      "update_notes",
      "type_text",
      "select_option",
      "set_checkbox",
      "upload_file",
      "click_element",
      "clarify",
    ],
    discouragedTools: ["done", "click_coordinates", "press_key"],
    capabilityNeeds: ["read_context", "update_record", "verify_saved"],
    contextScope: "turn",
    verifierMode: "hybrid",
    atomic: true,
    notes: [
      "Ashby application labels may look like questions; fill them as fields and do not turn them into analysis tasks.",
      "Copy long user-supplied answers exactly, including paragraph breaks and sentence grouping.",
      'Verify text inputs and textareas through read_element(attribute="value") before reporting ready state.',
      "Submit Application is a final consequential action and must remain approval-gated.",
    ],
  },
  {
    id: "servicenow-record-form",
    name: "ServiceNow Record Form",
    description:
      "Fill, verify, and submit ServiceNow record forms by field label/name with form-state readback.",
    tags: ["workflow", "forms", "servicenow", "record"],
    packId: "servicenow-platform",
    triggers: [
      "servicenow record form",
      "create a new incident",
      "create a new change request",
      "value for field",
    ],
    maturity: "candidate",
    preferredTools: [
      "configure_servicenow_form",
      "read_page",
      "open_servicenow_module",
      "done",
      "update_notes",
    ],
    discouragedTools: [
      "click_element",
      "type_text",
      "select_option",
      "press_key",
      "click_coordinates",
    ],
    contextScope: "turn",
    verifierMode: "deterministic",
    notes: [
      "Use the ServiceNow form helper for both field configuration and final submit.",
      "Verify field readback before submit and record evidence after submit.",
    ],
  },
  {
    id: "inline-edit-surface",
    name: "Inline Edit Surface",
    description:
      "Edit a value directly inside a grid cell, table row, inline rename field, or other in-place editor, then commit and verify the change.",
    tags: ["workflow", "editing", "inline-edit", "grid", "rename"],
    triggers: [
      "edit spreadsheet cell",
      "rename inline",
      "update table cell value",
      "change a value in place",
    ],
    maturity: "candidate",
    preferredTools: [
      "click_element",
      "press_key",
      "type_text",
      "read_page",
      "read_element",
      "find_element",
    ],
    discouragedTools: ["click_coordinates", "done"],
    contextScope: "turn",
    verifierMode: "deterministic",
    notes: [
      "Commit the edit before calling done.",
      "Prefer tagged targets over coordinate clicks for inline editors.",
    ],
  },
  {
    id: "continuation-edit",
    name: "Continuation Edit",
    description:
      "Revise prior work in the same workspace while preserving stable prior constraints unless explicitly overridden.",
    tags: ["workflow", "continuation", "editing", "context"],
    triggers: [
      "change previous draft",
      "revise prior answer",
      "continue previous task",
    ],
    maturity: "candidate",
    preferredTools: ["read_page", "update_notes", "type_text"],
    discouragedTools: ["navigate"],
    contextScope: "workspace",
    verifierMode: "hybrid",
    notes: ["Apply the requested delta, not a full rewrite unless necessary."],
  },
  {
    id: "cross-tab-compare",
    name: "Cross Tab Compare",
    description:
      "Collect facts from explicitly separate tabs or pages, normalize them, then compare or report the requested multi-source values after evidence is gathered.",
    tags: ["workflow", "comparison", "tabs", "context"],
    triggers: [
      "compare tabs",
      "read both tabs",
      "collect values from two pages",
      "compare page 1 and page N",
      "compare overview and reports",
    ],
    maturity: "candidate",
    preferredTools: ["read_page", "switch_tab", "read_element", "update_notes"],
    discouragedTools: [
      "navigate",
      "go_back",
      "click_coordinates",
      "right_click",
      "done",
    ],
    contextScope: "workspace",
    verifierMode: "deterministic",
    notes: [
      "Gather all required facts before synthesizing.",
      "Do not use for single-page configurators, ordinary report-tab navigation, inline edits, or list-review recommendations.",
      "Use list_tabs/switch_tab only for explicit browser-tab work. For in-page tabs such as Overview or Reports, use the visible page controls or previously gathered step results.",
      "When prior completed steps already contain the facts needed for the comparison, synthesize from that evidence before navigating or switching tabs.",
    ],
  },
  {
    id: "modal-overlay-recovery",
    name: "Modal Overlay Recovery",
    description:
      "Clear blocking overlays: run dismiss_overlays first, then click the close control of anything it reports as CSS-hidden or surviving, re-grounding after each dismissal.",
    tags: ["workflow", "modal", "overlay", "popup", "banner", "recovery"],
    triggers: [
      "close popup",
      "dismiss modal",
      "cookie banner",
      "newsletter popup",
      "blocking overlay",
    ],
    maturity: "candidate",
    preferredTools: [
      "dismiss_overlays",
      "read_page",
      "click_element",
      "press_key",
      "read_element",
    ],
    discouragedTools: ["navigate", "type_text"],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "dismiss_overlays clicks real close buttons where it finds them and reports which overlays were only CSS-hidden — handle those by clicking their close control directly.",
      "Re-read after each dismissal to verify it is gone and to refresh element IDs.",
      "Call done after ALL blocking overlays are confirmed gone.",
      "If read_page or inspect_hidden shows no cookie, newsletter, popup, banner, modal, close, dismiss, or accept controls remain, stop searching and call done.",
    ],
  },
  {
    id: "navigate-read-return",
    name: "Navigate Read Return",
    description:
      "Navigate to a target page, extract the needed information, then return to the original page to continue.",
    tags: ["workflow", "navigation", "lookup", "round-trip"],
    triggers: [
      "go to page and come back",
      "look up information then return",
      "find details on another page",
      "check job listing and return",
      "round-trip lookup",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "navigate",
      "go_back",
      "click_element",
      "read_element",
      "update_notes",
    ],
    discouragedTools: ["done"],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "Capture the needed fact before navigating away from the target page.",
      "Verify the return landed on the expected origin page before continuing.",
    ],
  },
  {
    id: "multi-tab-checklist-workflow",
    name: "Multi-Tab Checklist Workflow",
    description:
      "Work through a source list or checklist where each item requires opening a target page in another tab, completing or extracting item-specific work, returning to the source tab, and recording progress before repeating.",
    packId: "procurement-workflows",
    tags: ["workflow", "tabs", "checklist", "multi-tab", "review"],
    triggers: [
      "open each item in a new tab",
      "open links in separate tabs then return to the list",
      "review checklist items across tabs and mark them done",
      "procurement list store tabs",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "create_tab",
      "switch_tab",
      "click_element",
      "type_text",
      "set_checkbox",
      "update_notes",
    ],
    discouragedTools: ["navigate", "go_back", "click_coordinates", "done"],
    contextScope: "workspace",
    verifierMode: "hybrid",
    notes: [
      "Use the source row or checklist item as the source of truth for the target page and item-specific objective.",
      "Open or reuse a target tab, complete the target work, record compact evidence in notes, then switch back to the source tab.",
      "Mark or record source progress only after the target tab work is actually completed or the required evidence is captured.",
    ],
  },
  {
    id: "paginated-table-scan",
    name: "Paginated Table Scan",
    description:
      "Scan a paginated table or data list exhaustively before answering aggregate questions such as highest, lowest, largest, or smallest value.",
    tags: ["workflow", "pagination", "table", "aggregate", "scan"],
    triggers: [
      "highest value in a paginated table",
      "lowest amount across all pages",
      "scan all table rows before answering",
      "showing rows X-Y of Z",
      "page through a directory or records table",
    ],
    maturity: "candidate",
    preferredTools: ["read_page", "click_element", "update_notes"],
    discouragedTools: [
      "find_element",
      "read_element",
      "type_text",
      "press_key",
      "select_option",
      "set_checkbox",
      "scroll_page",
      "inspect_hidden",
      "xray_page",
      "execute_js",
      "click_coordinates",
      "create_tab",
      "list_tabs",
      "done",
    ],
    contextScope: "workspace",
    verifierMode: "hybrid",
    notes: [
      "A visible page is only a sample unless the pagination range proves it is the whole dataset.",
      "Track seen ranges and the current best candidate in notes after each page.",
      "Use the visible Next control or the next sequential page-number button for forward coverage; if one does not advance the visible range, switch to the other.",
    ],
  },
  {
    id: "paginated-record-lookup",
    name: "Paginated Record Lookup",
    description:
      "Find one or a small number of named records in a paginated, searchable, or list-like data surface before extracting the requested field.",
    tags: ["workflow", "pagination", "table", "lookup", "search"],
    triggers: [
      "find a specific record in a table",
      "search for a named employee or ticket",
      "look up a row in a directory",
      "find post number in a feed",
      "locate an item across paginated results",
    ],
    maturity: "candidate",
    preferredTools: [
      "read_page",
      "find_element",
      "type_text",
      "click_element",
      "scroll_page",
      "wait",
      "update_notes",
    ],
    discouragedTools: [
      "read_element",
      "press_key",
      "inspect_hidden",
      "xray_page",
      "execute_js",
      "click_coordinates",
      "create_tab",
      "list_tabs",
      "done",
    ],
    contextScope: "workspace",
    verifierMode: "hybrid",
    notes: [
      "Use visible search or filter controls before manual pagination when the target is specific.",
      "When no search/filter exists, advance sequentially with Next or scroll_page for lazy-loaded feeds while tracking searched pages or ranges in notes.",
      "Do not answer from a near match; verify the target row identity before extracting the requested field.",
    ],
  },
  {
    id: "list-detail-review-loop",
    name: "List Detail Review Loop",
    description:
      "Review a series of visible list items by opening each detail view, capturing the requested facts, and returning to the list before continuing.",
    tags: ["workflow", "list", "detail", "review", "round-trip"],
    triggers: [
      "review all listings",
      "review the job listings and recommend matches",
      "open each item and come back",
      "read each detail page then return to the list",
      "review job listings one by one",
    ],
    maturity: "candidate",
    preferredTools: [
      "click_element",
      "read_page",
      "update_notes",
      "scroll_page",
      "find_element",
    ],
    discouragedTools: ["read_element", "navigate", "go_back", "done"],
    contextScope: "turn",
    verifierMode: "hybrid",
    notes: [
      "Enumerate the requested visible review set once before opening detail pages.",
      "Track reviewed item names in notes so an item is not reopened or skipped.",
      "When a tagged list action is already visible, click it directly instead of inspecting its attributes.",
      "Use one detail-page read to extract the facts, then return to the list immediately.",
      "Prefer the page's own back or return control over browser history when the detail view appears in-place.",
      "For recommendation or best-match tasks, treat the visible listings as the review set unless the user narrows the scope.",
    ],
  },
];
