import type { ModelPricing } from "./pricing";

export const DEFAULT_MODEL_PRICING: ModelPricing[] = [
  {
    providerId: "groq",
    model: "openai/gpt-oss-120b",
    inputUsdPerMillion: 0.15,
    outputUsdPerMillion: 0.6,
    cachedInputUsdPerMillion: 0.075,
    effectiveDate: "2026-04-19",
    sourceUrl: "https://console.groq.com/docs/model/openai/gpt-oss-120b",
    confidence: "official",
  },
  {
    providerId: "groq",
    model: "meta-llama/llama-4-scout-17b-16e-instruct",
    inputUsdPerMillion: 0.11,
    outputUsdPerMillion: 0.34,
    effectiveDate: "2026-04-19",
    sourceUrl:
      "https://console.groq.com/docs/model/meta-llama/llama-4-scout-17b-16e-instruct",
    confidence: "official",
  },
  {
    providerId: "openrouter",
    model: "openai/gpt-oss-120b",
    inputUsdPerMillion: 0.039,
    outputUsdPerMillion: 0.19,
    effectiveDate: "2026-02-18",
    sourceUrl: "https://openrouter.ai/openai/gpt-oss-120b",
    confidence: "official",
  },
  {
    providerId: "openrouter",
    model: "minimax/minimax-m2.5",
    inputUsdPerMillion: 0.118,
    outputUsdPerMillion: 0.99,
    effectiveDate: "2026-04-19",
    sourceUrl: "https://openrouter.ai/minimax/minimax-m2.5",
    confidence: "official",
  },
  {
    providerId: "openrouter",
    model: "google/gemini-2.5-flash-lite",
    inputUsdPerMillion: 0.1,
    outputUsdPerMillion: 0.4,
    effectiveDate: "2026-04-19",
    sourceUrl: "https://openrouter.ai/google/gemini-2.5-flash-lite",
    confidence: "official",
  },
  {
    providerId: "openrouter",
    model: "google/gemini-2.5-flash",
    inputUsdPerMillion: 0.3,
    outputUsdPerMillion: 2.5,
    effectiveDate: "2026-04-19",
    sourceUrl: "https://openrouter.ai/google/gemini-2.5-flash",
    confidence: "official",
  },
  {
    providerId: "fireworks",
    model: "openai/gpt-oss-120b",
    inputUsdPerMillion: 0.15,
    outputUsdPerMillion: 0.6,
    effectiveDate: "2026-04-19",
    sourceUrl: "https://fireworks.ai/pricing",
    confidence: "official",
  },
  {
    providerId: "fireworks",
    // The Fireworks API id form (the judge seat bills under this id; the
    // catalog-style openai/... row above is kept for UI/catalog lookups).
    model: "accounts/fireworks/models/gpt-oss-120b",
    inputUsdPerMillion: 0.15,
    outputUsdPerMillion: 0.6,
    effectiveDate: "2026-04-19",
    sourceUrl: "https://fireworks.ai/pricing",
    confidence: "official",
  },
  {
    providerId: "fireworks",
    model: "qwen/qwen3-vl-30b-a3b-instruct",
    inputUsdPerMillion: 0.15,
    outputUsdPerMillion: 0.6,
    effectiveDate: "2026-04-19",
    sourceUrl: "https://fireworks.ai/pricing",
    confidence: "official",
  },
  {
    providerId: "fireworks",
    model: "accounts/fireworks/models/kimi-k2p7-code",
    inputUsdPerMillion: 0.95,
    outputUsdPerMillion: 4.0,
    cachedInputUsdPerMillion: 0.19,
    effectiveDate: "2026-06-12",
    sourceUrl: "https://fireworks.ai/models/fireworks/kimi-k2p7-code",
    confidence: "official",
  },
  {
    providerId: "fireworks",
    model: "accounts/fireworks/routers/kimi-k2p6-turbo",
    inputUsdPerMillion: 2.0,
    outputUsdPerMillion: 8.0,
    cachedInputUsdPerMillion: 0.3,
    effectiveDate: "2026-05-29",
    sourceUrl: "https://docs.fireworks.ai/serverless/pricing",
    confidence: "official",
  },
  {
    providerId: "fireworks",
    model: "accounts/fireworks/routers/kimi-k2p5-turbo",
    inputUsdPerMillion: 0.99,
    outputUsdPerMillion: 4.94,
    cachedInputUsdPerMillion: 0.16,
    effectiveDate: "2026-04-19",
    sourceUrl: "https://fireworks.ai/pricing",
    confidence: "official",
  },
  {
    providerId: "fireworks",
    model: "accounts/fireworks/routers/kimi-k2p5",
    inputUsdPerMillion: 0.6,
    outputUsdPerMillion: 3.0,
    cachedInputUsdPerMillion: 0.1,
    effectiveDate: "2026-04-19",
    sourceUrl: "https://fireworks.ai/pricing",
    confidence: "official",
  },
  {
    providerId: "fireworks",
    model: "accounts/fireworks/models/minimax-m2p5",
    inputUsdPerMillion: 0.3,
    outputUsdPerMillion: 1.2,
    cachedInputUsdPerMillion: 0.03,
    effectiveDate: "2026-04-19",
    sourceUrl: "https://fireworks.ai/pricing",
    confidence: "official",
  },
  {
    providerId: "fireworks",
    // minimax-m3: unified-VL executor candidate under A/B vs kimi-k2p7-code
    // (2026-07-17). Fireworks serverless rate, confirmed against the M3 launch
    // and pricing pages; prompt caching cuts effective input ~90%.
    model: "accounts/fireworks/models/minimax-m3",
    inputUsdPerMillion: 0.3,
    outputUsdPerMillion: 1.2,
    cachedInputUsdPerMillion: 0.03,
    effectiveDate: "2026-07-17",
    sourceUrl: "https://fireworks.ai/blog/minimax-m3-launch",
    confidence: "official",
  },
  {
    providerId: "fireworks",
    // GLM 5.2 as planner/orchestrator candidate. Pricing is a placeholder
    // estimate — verify against Fireworks' published rate before trusting cost.
    model: "accounts/fireworks/models/glm-5p2",
    inputUsdPerMillion: 0.55,
    outputUsdPerMillion: 2.19,
    effectiveDate: "2026-06-24",
    sourceUrl: "https://fireworks.ai/pricing",
    confidence: "best_effort",
  },
  {
    providerId: "moonshot",
    model: "kimi-k2.6",
    inputUsdPerMillion: 0.95,
    outputUsdPerMillion: 4.0,
    cachedInputUsdPerMillion: 0.16,
    effectiveDate: "2026-04-22",
    sourceUrl: "https://platform.kimi.ai/docs/pricing/chat-k26",
    confidence: "official",
  },
  {
    providerId: "moonshot",
    model: "kimi-k2.5",
    inputUsdPerMillion: 0.6,
    outputUsdPerMillion: 3.0,
    cachedInputUsdPerMillion: 0.1,
    effectiveDate: "2026-04-22",
    sourceUrl: "https://platform.kimi.ai/docs/pricing/chat-k25",
    confidence: "official",
  },
  {
    providerId: "deepseek",
    model: "deepseek-v4-flash",
    inputUsdPerMillion: 0.14,
    outputUsdPerMillion: 0.28,
    cachedInputUsdPerMillion: 0.0028,
    effectiveDate: "2026-04-26",
    sourceUrl: "https://api-docs.deepseek.com/quick_start/pricing",
    confidence: "official",
  },
  {
    providerId: "deepseek",
    model: "deepseek-v4-pro",
    inputUsdPerMillion: 0.435,
    outputUsdPerMillion: 0.87,
    cachedInputUsdPerMillion: 0.003625,
    effectiveDate: "2026-04-26",
    sourceUrl: "https://api-docs.deepseek.com/quick_start/pricing",
    confidence: "official",
  },
  {
    providerId: "cerebras",
    // gemma-4-31b executor eval (2026-07-09). Rate from the Cerebras pricing
    // page; caching discount not published, so cachedInputUsdPerMillion is
    // omitted (cost falls back to the full input rate for cached tokens).
    model: "gemma-4-31b",
    inputUsdPerMillion: 0.99,
    outputUsdPerMillion: 1.49,
    effectiveDate: "2026-07-09",
    sourceUrl: "https://cloud.cerebras.ai",
    confidence: "official",
  },
  {
    providerId: "xiaomi",
    model: "mimo-v2-omni",
    inputUsdPerMillion: 0,
    outputUsdPerMillion: 0,
    effectiveDate: "2026-04-29",
    sourceUrl: "https://platform.xiaomimimo.com/#/docs",
    confidence: "best_effort",
  },
  {
    providerId: "xiaomi",
    model: "mimo-v2-pro",
    inputUsdPerMillion: 0,
    outputUsdPerMillion: 0,
    effectiveDate: "2026-04-29",
    sourceUrl: "https://platform.xiaomimimo.com/#/docs",
    confidence: "best_effort",
  },
  {
    providerId: "xiaomi",
    model: "mimo-v2-flash",
    inputUsdPerMillion: 0,
    outputUsdPerMillion: 0,
    effectiveDate: "2026-04-29",
    sourceUrl: "https://platform.xiaomimimo.com/#/docs",
    confidence: "best_effort",
  },
  {
    providerId: "openrouter",
    model: "openai/gpt-5.4-mini",
    inputUsdPerMillion: 0.75,
    outputUsdPerMillion: 4.5,
    effectiveDate: "2026-04-19",
    sourceUrl: "https://openrouter.ai/openai/gpt-5.4-mini",
    confidence: "official",
  },
];
