/**
 * VL executor screenshot capture (LP-17b CM-5).
 *
 * Extracted verbatim from AgentLoop.captureScreenshotForVLExecutor (dispatch-
 * host idiom, shrinking the ratchet-guarded loop.ts), plus one new behavior:
 * when the page fingerprint is unchanged since the previous capture, REUSE
 * the previous dataUrl instead of re-capturing — identical bytes, identical
 * prompt block, zero information loss, no captureVisibleTab/transform
 * latency. Canvas-bearing pages are exempt (visual state can change without
 * the DOM changing). Precedent: passive-monitor/controller.ts no_change skip.
 */
import type { DomSnapshot } from "../../types";
import { transformScreenshot } from "../perception/screenshot-transform";
import { setCachedScreenshot } from "./screenshot-cache";
import { withPresenceSuspended } from "./capture-guard";
import { getSnapshotFingerprint } from "./loop-helpers";
import { extractPerceptionPageSignals } from "../../utils/perception-mode";

export interface VLScreenshotHost {
  context: {
    getSnapshot(): DomSnapshot | null;
    setScreenshotForExecutor(dataUrl: string | null): void;
    setPageInterpretation(value: string | null): void;
  };
  perception: { setScreenshotUrl(url: string | null): void };
  traceRecorder: {
    recordEvent(type: string, data?: Record<string, unknown>): void;
    recordPerception(entry: Record<string, unknown>, screenshot?: string): void;
  } | null;
  log: {
    warn(
      category: string,
      message: string,
      data?: Record<string, unknown>,
    ): void;
  };
  imagePromptBudgetAllows(count: number): boolean;
  recordImagePromptBudgetExhausted(count: number, source: string): void;
  captureVisibleTabWithRetry(
    windowId: number | undefined,
    options: { format: "jpeg" | "png"; quality?: number },
  ): Promise<string>;
}

export interface VLScreenshotState {
  lastFingerprint: string | null;
  lastDataUrl: string | null;
}

export function createVLScreenshotState(): VLScreenshotState {
  return { lastFingerprint: null, lastDataUrl: null };
}

/** Capture (or reuse) the screenshot for VL executor injection. */
export async function captureVLExecutorScreenshot(
  host: VLScreenshotHost,
  tabId: number,
  state: VLScreenshotState,
): Promise<void> {
  const snapshot = host.context.getSnapshot();
  if (!snapshot) {
    host.context.setScreenshotForExecutor(null);
    host.context.setPageInterpretation(null);
    return;
  }
  if (!host.imagePromptBudgetAllows(1)) {
    host.recordImagePromptBudgetExhausted(1, "vl_executor_screenshot");
    host.context.setScreenshotForExecutor(null);
    host.context.setPageInterpretation(null);
    host.perception.setScreenshotUrl(null);
    host.traceRecorder?.recordPerception(
      {
        interpretation:
          "[VL mode] Screenshot omitted because the image prompt budget is exhausted.",
        model: "none (image budget)",
        durationMs: 0,
        cached: false,
        mode: "element_only",
        source: "fallback",
        freshnessReason: "dom_fallback",
        fallbackReason: "image_budget_exhausted",
        screenshotStatus: "not_requested",
      },
      undefined,
    );
    return;
  }

  // LP-17b CM-5: unchanged page → reuse the previous screenshot bytes.
  const fingerprint = getSnapshotFingerprint(snapshot);
  if (
    state.lastDataUrl &&
    state.lastFingerprint === fingerprint &&
    !extractPerceptionPageSignals(snapshot).hasCanvas
  ) {
    host.context.setScreenshotForExecutor(state.lastDataUrl);
    host.context.setPageInterpretation(null);
    host.perception.setScreenshotUrl(state.lastDataUrl);
    host.traceRecorder?.recordEvent("vl_screenshot_reused", { tabId });
    return;
  }

  try {
    const tab = await chrome.tabs.get(tabId);
    if (!tab.active) {
      try {
        await chrome.tabs.update(tabId, { active: true });
      } catch {
        /* tab may be closed */
      }
    }
    // q90: the LP-9 transform re-encodes at q85 — see refreshPerception.
    // LP-24: presence cursor is hidden for the capture (RFC §6).
    const captured = await withPresenceSuspended(tabId, () =>
      host.captureVisibleTabWithRetry(tab.windowId, {
        format: "jpeg",
        quality: 90,
      }),
    );
    // LP-9: own resolution/format/scale before anything downstream sees it.
    const transformed = await transformScreenshot(captured);
    const dataUrl = transformed.dataUrl;
    host.traceRecorder?.recordEvent("screenshot_transform", {
      scaleFactor: transformed.scaleFactor,
      width: transformed.width,
      height: transformed.height,
      path: "vl_executor",
    });
    setCachedScreenshot(tabId, dataUrl, {
      scaleFactor: transformed.scaleFactor,
      width: transformed.width,
      height: transformed.height,
    });
    state.lastFingerprint = fingerprint;
    state.lastDataUrl = dataUrl;
    host.context.setScreenshotForExecutor(dataUrl);
    host.context.setPageInterpretation(null); // VL instructions generated by context
    host.perception.setScreenshotUrl(dataUrl); // keep for trace recording
    // Record synthetic perception entry so trace viewer shows the screenshot
    host.traceRecorder?.recordPerception(
      {
        interpretation:
          "[VL mode] Screenshot sent directly to executor — no separate perception call.",
        model: "none (unified VL)",
        durationMs: 0,
        cached: false,
        mode: "vl_screenshot_only",
        source: "fresh",
        freshnessReason: "vl_screenshot",
        screenshotStatus: "captured",
      },
      dataUrl,
    );
  } catch (e: unknown) {
    // Capture failed — fall back to 2-call pipeline for this turn. Stale
    // reuse state is cleared so the next turn re-captures.
    state.lastFingerprint = null;
    state.lastDataUrl = null;
    host.log.warn(
      "agent",
      "VL screenshot capture failed, falling back to perception",
      {
        error: (e as { message?: string })?.message,
        tabId,
      },
    );
    host.context.setScreenshotForExecutor(null);
    host.context.setPageInterpretation(null);
  }
}
