import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, extname, join, relative, resolve } from "node:path";
import { parse as parseYaml } from "yaml";

type PromptFrontmatter = {
  id: string;
  version: string;
  description: string;
};

type CompiledPrompt = {
  id: string;
  version: string;
  description: string;
  template: string;
  sourcePath: string;
  hash: string;
};

function hashPrompt(text: string): string {
  let hash = 5381;
  for (let i = 0; i < text.length; i += 1) {
    hash = (hash * 33) ^ text.charCodeAt(i);
  }
  return (hash >>> 0).toString(16).padStart(8, "0");
}

function walkMarkdownFiles(root: string): string[] {
  const out: string[] = [];
  const stack = [root];
  while (stack.length > 0) {
    const dir = stack.pop()!;
    const entries = readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
      } else if (entry.isFile() && extname(entry.name).toLowerCase() === ".md") {
        if (basename(entry.name).toLowerCase() === "readme.md") continue;
        out.push(full);
      }
    }
  }
  return out.sort();
}

function parsePromptFile(path: string): CompiledPrompt {
  const raw = readFileSync(path, "utf-8");
  if (!raw.startsWith("---\n")) {
    throw new Error(`Missing frontmatter in ${path}`);
  }
  const end = raw.indexOf("\n---\n", 4);
  if (end < 0) {
    throw new Error(`Unterminated frontmatter in ${path}`);
  }

  const fmRaw = raw.slice(4, end);
  const body = raw.slice(end + 5).trim();
  if (!body) {
    throw new Error(`Empty template body in ${path}`);
  }

  const fm = parseYaml(fmRaw) as PromptFrontmatter;
  if (!fm || typeof fm !== "object") {
    throw new Error(`Invalid frontmatter in ${path}`);
  }
  if (!fm.id || !fm.version || !fm.description) {
    throw new Error(`Frontmatter must include id/version/description in ${path}`);
  }

  return {
    id: String(fm.id),
    version: String(fm.version),
    description: String(fm.description),
    template: body,
    sourcePath: path,
    hash: hashPrompt(body),
  };
}

function toGeneratedTs(prompts: CompiledPrompt[], root: string): string {
  const header =
    "/* eslint-disable */\n" +
    "// Auto-generated by scripts/build-prompts.ts\n" +
    "// Do not edit manually.\n\n" +
    'import { PromptDefinition, PromptDescriptor } from "./types";\n\n';

  const promptEntries = prompts
    .map((p) => {
      const rel = relative(root, p.sourcePath).replace(/\\/g, "/");
      const template = JSON.stringify(p.template);
      return (
        `  ${JSON.stringify(p.id)}: {\n` +
        `    id: ${JSON.stringify(p.id)},\n` +
        `    version: ${JSON.stringify(p.version)},\n` +
        `    description: ${JSON.stringify(p.description)},\n` +
        `    template: ${template},\n` +
        `  }, // ${rel}\n`
      );
    })
    .join("");

  const descriptorEntries = prompts
    .map(
      (p) =>
        `  ${JSON.stringify(p.id)}: { id: ${JSON.stringify(p.id)}, version: ${JSON.stringify(p.version)}, hash: ${JSON.stringify(p.hash)} },\n`,
    )
    .join("");

  return (
    header +
    "export const GENERATED_PROMPTS = {\n" +
    promptEntries +
    "} as const satisfies Record<string, PromptDefinition>;\n\n" +
    "export const GENERATED_PROMPT_DESCRIPTORS = {\n" +
    descriptorEntries +
    "} as const satisfies Record<string, PromptDescriptor>;\n"
  );
}

function main(): void {
  const repoRoot = resolve(import.meta.dir, "..");
  const promptsRoot = join(repoRoot, "prompts");
  const outDir = join(repoRoot, "src", "prompts");
  const outTs = join(outDir, "generated.ts");
  const outManifest = join(outDir, "manifest.json");

  const files = walkMarkdownFiles(promptsRoot);
  if (files.length === 0) {
    throw new Error(`No prompt markdown files found under ${promptsRoot}`);
  }

  const prompts = files.map(parsePromptFile);
  const idSet = new Set<string>();
  for (const p of prompts) {
    if (idSet.has(p.id)) {
      throw new Error(`Duplicate prompt id "${p.id}"`);
    }
    idSet.add(p.id);
  }

  mkdirSync(outDir, { recursive: true });
  writeFileSync(outTs, toGeneratedTs(prompts, repoRoot), "utf-8");

  const manifest = prompts.map((p) => ({
    id: p.id,
    version: p.version,
    hash: p.hash,
    description: p.description,
    sourcePath: relative(repoRoot, p.sourcePath).replace(/\\/g, "/"),
  }));
  writeFileSync(outManifest, JSON.stringify(manifest, null, 2) + "\n", "utf-8");

  console.log(
    `[prompts] compiled ${prompts.length} templates -> ${relative(repoRoot, outTs)}`,
  );
}

main();
